//! Generate native user-service definitions without shell interpolation.
use std::path::{Path, PathBuf};

pub struct Definition {
    pub name: String,
    pub executable: PathBuf,
    pub runtime: PathBuf,
    pub arguments: Vec<String>,
}

impl Definition {
    pub fn systemd(&self) -> Result<String, &'static str> {
        validate_name(&self.name)?;
        let mut command = vec![
            "/usr/bin/env".into(),
            "--".into(),
            quote(&text(&self.executable)?)?,
        ];
        command.extend(
            self.arguments
                .iter()
                .map(|arg| quote(arg))
                .collect::<Result<Vec<_>, _>>()?,
        );
        // Output directives accept one path including spaces; specifiers still expand.
        let log = text(&self.runtime.join("daemon.log"))?.replace('%', "%%");
        Ok(format!("# Generated by jailgun service unit; accounts and results remain in the private runtime.\n[Unit]\nDescription=Jailgun concept service\nStartLimitIntervalSec=300\nStartLimitBurst=3\n\n[Service]\nType=exec\nExecStart={}\nRestart=on-failure\nRestartSec=10\nTimeoutStopSec=60\nKillMode=mixed\nUMask=0077\nStandardInput=null\nStandardOutput=null\nStandardError=append:{}\n\n[Install]\nWantedBy=default.target\n", command.join(" "), log))
    }

    pub fn launchd(&self) -> Result<String, &'static str> {
        validate_name(&self.name)?;
        let mut args = vec![text(&self.executable)?];
        args.extend(self.arguments.clone());
        let args = args
            .iter()
            .map(|arg| xml(arg).map(|arg| format!("    <string>{arg}</string>")))
            .collect::<Result<Vec<_>, _>>()?
            .join("\n");
        let log = xml(&text(&self.runtime.join("daemon.log"))?)?;
        let name = &self.name;
        Ok(format!("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\"><dict>\n  <key>Label</key><string>{name}</string>\n  <key>ProgramArguments</key><array>\n{args}\n  </array>\n  <key>RunAtLoad</key><true/>\n  <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>\n  <key>ThrottleInterval</key><integer>10</integer>\n  <key>ExitTimeOut</key><integer>60</integer>\n  <key>Umask</key><integer>63</integer>\n  <key>StandardOutPath</key><string>/dev/null</string>\n  <key>StandardErrorPath</key><string>{log}</string>\n</dict></plist>\n"))
    }
}

fn text(path: &Path) -> Result<String, &'static str> {
    let value = path.to_str().ok_or("Startup paths must be UTF-8")?;
    validate(value)?;
    if !path.is_absolute() {
        return Err("Startup paths must be absolute");
    }
    Ok(value.into())
}
fn validate(value: &str) -> Result<(), &'static str> {
    if value.chars().any(char::is_control) {
        Err("Startup values cannot contain control characters")
    } else {
        Ok(())
    }
}
fn quote(value: &str) -> Result<String, &'static str> {
    validate(value)?;
    let value = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('%', "%%")
        .replace('$', "$$");
    Ok(format!("\"{value}\""))
}
fn xml(value: &str) -> Result<String, &'static str> {
    validate(value)?;
    Ok(value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;"))
}

pub fn validate_name(value: &str) -> Result<(), &'static str> {
    if !value
        .as_bytes()
        .first()
        .is_some_and(u8::is_ascii_alphanumeric)
        || value.len() > 128
        || value == "."
        || value == ".."
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"._-".contains(&byte))
    {
        Err("Service names require 1–128 ASCII letters, digits, dots, underscores or hyphens")
    } else {
        Ok(())
    }
}
