#!/usr/bin/env node
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { randomUUID } from 'node:crypto';
import { mkdir, readFile, writeFile, realpath } from 'node:fs/promises';
import { basename, dirname, join, resolve } from 'node:path';
import { createServer } from 'node:net';
import { fileHash } from './distribution/files.mjs';
import { checkStartup } from './distribution/startup-proof.mjs';
import { checkRemoval } from './distribution/removal-proof.mjs';

const archive = resolve(process.argv[2]);
const checksums = (await readFile(join(dirname(archive), 'SHA256SUMS'), 'utf8')).trim().split('\n').map(line => line.trim().split(/\s+/));
const sums = checksums.filter(([, name]) => name === basename(archive));
assert.equal(sums.length, 1, 'Archive needs exactly one checksum entry');
assert.equal(await fileHash(archive), sums[0][0], 'Package checksum mismatch');
const installerSums = checksums.filter(([, name]) => name === 'install.sh');
assert.equal(installerSums.length, 1, 'Standalone installer needs exactly one checksum entry');
assert.equal(await fileHash(join(dirname(archive), 'install.sh')), installerSums[0][0], 'Standalone installer checksum mismatch');
const execute = promisify(execFile);
const command = (program, args, options = {}) => execute(program, args, { timeout: 60_000, maxBuffer: 4 * 1024 * 1024, ...options });
const listing = (await command('tar', ['-tzf', archive])).stdout.trim().split('\n');
assert.ok(listing.every(path => /^\.\/[A-Za-z0-9_@.+/-]+$/.test(path) && path.slice(2).split('/').every(part => part && part !== '.' && part !== '..')), 'Unsafe package member');
assert.equal(new Set(listing).size, listing.length, 'Duplicate package member');
assert.ok((await command('tar', ['-tvzf', archive])).stdout.trim().split('\n').every(line => line.startsWith('-')), 'Only regular files may be extracted');
const proof = resolve('target/package-proofs', randomUUID());
const installation = join(proof, 'installation with spaces $ % " &');
const unpacked = join(proof, 'verified download');
const working = join(proof, 'unrelated working directory');
const runtime = join(proof, 'private runtime');
for (const path of [unpacked, working, runtime, join(proof, 'temp')]) await mkdir(path, { recursive: true, mode: 0o700 });
await command('tar', ['-xzf', archive, '-C', unpacked]);
assert.equal(await fileHash(join(unpacked, 'install.sh')), installerSums[0][0], 'Standalone and bundled installers differ');
const binary = join(installation, 'bin/jailgun');
const env = { PATH: '/usr/bin:/bin', HOME: proof, TMPDIR: join(proof, 'temp'), LANG: 'C.UTF-8' };
const installerArgs = [join(unpacked, 'install.sh'), '--archive', archive, '--checksums', join(dirname(archive), 'SHA256SUMS'), '--prefix', installation];
await command('bash', installerArgs, { cwd: working, env });
const installed = await realpath(join(installation, 'lib/jailgun/current'));
const assets = join(installed, 'lib/jailgun');
const node = join(assets, 'node/bin/node');
const run = async (args, executable = binary) => (await command(executable, args, { cwd: working, env })).stdout;
const report = JSON.parse(await run([join(assets, 'verify-bundle.mjs'), installed], node));
const checks = ['standalone-installer-checksum', 'checksum-verified-shell-installation'];
await command('bash', installerArgs, { cwd: working, env });
assert.equal(await realpath(join(installation, 'lib/jailgun/current')), installed);checks.push('idempotent-reinstallation');
const damagedSums = join(proof, 'bad-checksums');await writeFile(damagedSums, `${'0'.repeat(64)}  ${basename(archive)}\n`);
await assert.rejects(command('bash', [join(unpacked, 'install.sh'), '--archive', archive, '--checksums', damagedSums, '--prefix', installation], { cwd: working, env }), /archive checksum mismatch/);
assert.equal(await realpath(join(installation, 'lib/jailgun/current')), installed);checks.push('checksum-failure-preserves-installation');
let daemon;
try {
  assert.equal((await run(['--version'])).trim(), `jailgun ${report.version}`);checks.push('installed-version');
  assert.ok((await run(['--help'], join(installation, 'bin/jailhard'))).includes('jailhard'));checks.push('installed-jailhard');
  assert.equal(JSON.parse(await run(['validate-config'])).deploy.enabled, false);checks.push('installed-default-config');
  const doctor = JSON.parse(await run(['doctor', '--runtime', runtime, '--headless', '--json']));
  assert.equal(doctor.status, 'ready');assert.equal(doctor.assets, assets);checks.push('installed-doctor');
  await run([join(assets, 'apps/chrome-bridge/bin/chrome-bridge.mjs'), '--self-test'], node);checks.push('compiled-archive-bridge');
  const listener = createServer();await new Promise(done => listener.listen(0, '127.0.0.1', done));
  const origin = `http://127.0.0.1:${listener.address().port}`;
  await new Promise(done => listener.close(done));
  await writeFile(join(runtime, 'daemon.json'), JSON.stringify({ url: origin, pid: 0xffffffff, version: report.version }), { mode: 0o600 });
  const first = JSON.parse(await run(['setup', '--runtime', runtime, '--headless', '--no-open', '--json']));
  daemon = JSON.parse(await readFile(join(runtime, 'daemon.json'), 'utf8'));
  assert.equal(daemon.url, origin);assert.ok(daemon.pid > 1 && daemon.pid < 0x7fffffff && daemon.pid !== process.pid);
  const credentialHash = await fileHash(join(runtime, 'operator-token'));
  const firstUrl = new URL(first.dashboard_url);
  const code = new URLSearchParams(firstUrl.hash.slice(1)).get('pair');
  const request = (path, options = {}) => fetch(`${origin}${path}`, { ...options, signal: AbortSignal.timeout(10_000) });
  assert.equal((await request('/api/accounts')).status, 401);
  const pairing = await request('/api/session/pair', { method: 'POST', headers: { origin, 'content-type': 'application/json' }, body: JSON.stringify({ code }) });
  assert.equal(pairing.status, 204);
  const cookie = pairing.headers.getSetCookie()[0].split(';')[0];
  assert.deepEqual(await (await request('/api/accounts', { headers: { cookie } })).json(), []);checks.push('pairing-and-private-api');
  const html = await (await request('/')).text();
  const asset = html.match(/src="(\/assets\/[^\"]+\.js)"/)?.[1];assert.ok(asset);
  assert.equal((await request(asset)).status, 200);checks.push('packaged-dashboard');
  assert.deepEqual(JSON.parse(await run(['accounts', 'list', '--runtime', runtime, '--json'])), []);
  const second = JSON.parse(await run(['setup', '--runtime', runtime, '--headless', '--no-open', '--json']));
  assert.notEqual(second.dashboard_url, first.dashboard_url);
  assert.equal((JSON.parse(await readFile(join(runtime, 'daemon.json'), 'utf8'))).pid, daemon.pid);
  assert.equal(await fileHash(join(runtime, 'operator-token')), credentialHash);checks.push('daemon-and-credential-reuse');
} finally {
  if (daemon?.pid > 1 && daemon.pid < 0x7fffffff && daemon.pid !== process.pid) {
    const stopped = JSON.parse(await run(['service', 'stop', '--runtime', runtime, '--json']));
    assert.equal(stopped.state, 'stopped');
    const repeated = JSON.parse(await run(['service', 'stop', '--runtime', runtime, '--json']));
    assert.equal(repeated.state, 'stopped');checks.push('authenticated-shutdown-and-idempotent-stop');
  }
}
checks.push(...await checkStartup({ binary, proof, run, env, working }));
checks.push(...await checkRemoval({ binary, installation, installed, runtime, proof, run }));
await writeFile(join(proof, 'evidence.json'), JSON.stringify({ generated_at: new Date().toISOString(), status: 'pass', command: 'node scripts/check-package.mjs <verified-archive>', exit_status: 0, archive_sha256: await fileHash(archive), source: report.source, platform: report.platform, version: report.version, checks, caveats: ['Executed outside the build working directory with executable-relative assets and system-only PATH.', 'The host checkout remained present; this is not clean-environment or live-provider acceptance.'] }, null, 2) + '\n', { mode: 0o600 });
console.log(`Packaged runtime checks passed: ${join(proof, 'evidence.json')}`);
